[package]
name = "auramesh-agents"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
log.workspace = true
auramesh-core = { path = "../auramesh-core" }
bollard = "0.16"
tokio.workspace = true